- app/assets/javascripts/events.coffee
- app/assets/stylesheets/events.scss
- app/controllers/events_controller.rb
- app/helpers/events_helper.rb
- app/models/event.rb
- app/views/events/index.html.erb
- config/routes.rb
- db/migrate/20181215180007_create_events.rb
- db/schema.rb
- test/controllers/events_controller_test.rb
- test/fixtures/events.yml
- test/models/event_test.rb
> Show events as bubbles

- Gemfile
- Gemfile.lock
- README.md
- app/views/events/index.html.erb
- docker-compose.yml
- poxa.conf
> Make nodes when poxa receives a message

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- config/routes.rb
> Web endpoint for publishing events to the screen

- app/controllers/events_controller.rb
> Broadcast two events when we hit the API

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- db/migrate/20181218023038_add_prior_event_to_event.rb
- db/schema.rb
> Make a string of events when there's an API call

- app/controllers/events_controller.rb
- app/models/event_handler.rb
> Event handler idea

- db/migrate/20181218023038_add_prior_event_to_event.rb
- db/schema.rb
> Create the right column name

- app/views/events/index.html.erb
> Make this bigger.

- config/routes.rb
> Let this work with a get request, too.

- app/controllers/events_controller.rb
- app/models/event_handler.rb
> Different flow

- .env
- config/environments/development.rb
> Reload files whenever they are edited

- app/controllers/events_controller.rb
> Dont forget to publish

- Gemfile
- Gemfile.lock
- app/controllers/events_controller.rb
- app/models/event.rb
- app/models/event_handler.rb
- app/models/web_request.rb
- config/routes.rb
- db/migrate/20181228023038_add_data_to_event.rb
- db/schema.rb
> Create a handler that will make web requests.

- app/models/event_handler.rb
- app/models/workflow.rb
> Multiple events

- app/controllers/events_controller.rb
- app/models/workflow.rb
- config/routes.rb
> Multiple event handlers

- app/controllers/events_controller.rb
- app/models/web_request.rb
- app/models/workflow.rb
> Event handlers need configuration

- app/controllers/events_controller.rb
- app/controllers/sequence_controller.rb
- app/views/sequence/new.html.erb
- config/routes.rb
> UI for creating a sequence of steps

- app/models/workflow.rb
- app/views/events/aggregate.html.erb
- app/views/sequence/new.html.erb
- config/routes.rb
- db/migrate/20190105200736_add_step_guid_to_events.rb
- db/schema.rb
- New Dashboard
- `step_guid` added to events
> Dashboard for event aggregation by step

- app/assets/javascripts/event-creation-app.js
- app/assets/javascripts/event-stream.js
- app/assets/javascripts/event-visualization.js
- app/views/events/aggregate.html.erb
- app/views/events/index.html.erb
- app/views/sequence/new.html.erb
> Reorganize JS

- Gemfile
- Gemfile.lock
- app/controllers/events_controller.rb
- app/models/event.rb
- app/models/event_handler.rb
- app/models/web_request.rb
- app/models/workflow.rb
> Symbolized hashes with a "spark"

- app/models/web_request.rb
- app/models/workflow.rb
@calebcauthon I am merging this, as it touches code that I need to change for my first demo.  It'll be very awkward to have a billion pull requests today to finish what I need to finish.
But the main idea here is that this will let us change the message of an event through the event handler config.  In doing this, I had to change the way the events are handled... all improvements.
> Event message

- app/models/workflow.rb
> There is no need to flatten these events now.

- app/models/workflow.rb
> Merging events data from the parent to the child

- app/models/event_formatter.rb
> Event formatter

- app/assets/javascripts/event-creation-app.js
- app/assets/javascripts/event-stream.js
- app/assets/javascripts/event-visualization.js
- app/controllers/events_controller.rb
- app/models/event_handler.rb
- app/models/web_request.rb
- app/models/workflow.rb
- app/views/sequence/new.html.erb
* Ability to create "tree"-style workflow rather than only "sequence"-style workflows
* simplify event controller a bit by removing the "sequence"-style workflow creation
>  Fire workflows using a tree structure

- app/controllers/events_controller.rb
- app/models/trigger.rb
> More trigger options

- app/controllers/events_controller.rb
- app/models/context_setter.rb
- app/models/workflow.rb
- app/models/workflow_result.rb
> Workflow context

- app/assets/javascripts/event-creation-app.js
- app/assets/javascripts/event-stream.js
- app/assets/javascripts/event-visualization.js
- app/views/events/aggregate.html.erb
- app/views/events/index.html.erb
- app/views/sequence/new.html.erb
I tested the /events/index, /events/aggregate, and /sequence/new endpoints, and they're still functional.
These are javascript refactors to encapsulate some of the logic.
> Refactor the diagram javascript

- overt/app/views/layouts/adminlte.html.erb
> Remove the turbolinks stuff to prevent some weird file access error.
